backend:
  name: gitlab
  repo: devon-wolf/portal-data-model
  branch: main
  auth_type: pkce
  app_id: 17365e6d95dc68a12025b781171cdac2e3f0170a5437438d1c90eb1d2effec69
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: solutions/test-solution/assets # there is actually a folder for each solution or partner, for this test I'll target the one for the target file

collections:
  - name: "solutions"
    label: "Solutions"
    # for now, just test on a single file
    # folder: "solutions"
    # create: true
    # slug: {{slug}}
    files:
      - file: "solutions/test-solution/solution.yml"
        label: "Test Solution"
        name: "test"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Group, name: group, widget: string }
          - { label: Disabled, name: disabled, widget: boolean }
          - {
              label: Main Focus,
              name: mainFocus,
              widget: object,
              fields:
                [
                  { label: Media, name: media, widget: image, required: false },
                  {
                    label: Description,
                    name: mainFocusDescription,
                    widget: text,
                    required: false,
                  },
                  {
                    label: Link,
                    name: link,
                    widget: object,
                    required: false,
                    fields:
                      [
                        {
                          label: Label,
                          name: label,
                          widget: string,
                          required: false,
                        },
                        {
                          label: URL,
                          name: link,
                          widget: string,
                          required: false,
                        },
                        {
                          label: Linked Asset Reference,
                          name: linkedAssetReference,
                          widget: string,
                          required: false,
                        },
                      ],
                  },
                ],
            }
          - {
              label: Sections,
              name: sections,
              widget: list,
              allow_add: true,
              required: false,
              fields:
                [
                  {
                    label: Category,
                    name: category,
                    widget: string,
                    required: false,
                  },
                  {
                    label: Entries,
                    name: entries,
                    widget: list,
                    allow_add: true,
                    required: false,
                    fields:
                      [
                        {
                          label: Label,
                          name: label,
                          widget: string,
                          required: false,
                        },
                        {
                          label: URL,
                          name: link,
                          widget: string,
                          required: false,
                        },
                        {
                          label: Description,
                          name: description,
                          widget: text,
                          required: false,
                        },
                      ],
                  },
                ],
            }
          - {
              label: Linked Assets,
              name: linkedAssets,
              widget: object,
              required: false,
              fields:
                [
                  {
                    label: Demo Video Example,
                    name: demo-video-example,
                    widget: object,
                    required: false,
                    fields:
                      [
                        {
                          label: Label,
                          name: label,
                          widget: string,
                          required: false,
                        },
                        {
                          label: URL,
                          name: link,
                          widget: string,
                          required: false,
                        },
                        {
                          label: Description,
                          name: description,
                          widget: text,
                          required: false,
                        },
                        {
                          label: Resource Type,
                          name: resourceType,
                          widget: string,
                          required: false,
                        },
                        {
                          label: Duration,
                          name: durationMinutes,
                          widget: number,
                          required: false,
                        },
                        {
                          label: Technical Level,
                          name: technicalLevel,
                          widget: number,
                          required: false,
                        },
                      ],
                  },
                ],
            }
