backend:
  name: gitlab
  repo: devon-wolf/portal-data-model
  branch: main
  auth_type: pkce
  app_id: 17365e6d95dc68a12025b781171cdac2e3f0170a5437438d1c90eb1d2effec69
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: solutions/test-solution/assets # there is actually a folder for each solution or partner, for this test I'll target the one for the target file

collections:
  - name: "solutions"
    label: "Solutions"
    # for now, just test on a single file
    # folder: "solutions"
    # create: true
    # slug: {{slug}}
    files:
      - file: "solutions/test-solution/solution.yml"
        label: "Test Solution"
        name: "test"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Group, name: group, widget: string }
          - { label: Disabled, name: disabled, widget: boolean }
          - {
              label: Main Focus,
              name: mainFocus,
              widget: object,
              fields:
                [
                  { label: Media, name: media, widget: image },
                  {
                    label: Description,
                    name: mainFocusDescription,
                    widget: text,
                  },
                  {
                    label: Link,
                    name: link,
                    widget: object,
                    fields:
                      [
                        { label: Label, name: label, widget: string },
                        { label: URL, name: link, widget: string },
                        {
                          label: Linked Asset Reference,
                          name: linkedAssetReference,
                          widget: string,
                        },
                      ],
                  },
                ],
            }
          - {
              label: Sections,
              name: sections,
              widget: list,
              fields:
                [
                  { label: Category, name: category, widget: string },
                  {
                    label: Entries,
                    name: entries,
                    widget: list,
                    fields:
                      [
                        { label: Label, name: label, widget: string },
                        { label: URL, name: link, widget: string },
                        { label: Description, name: description, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Linked Assets,
              name: linkedAssets,
              widget: object,
              fields:
                [
                  {
                    label: Demo Video Example,
                    name: demo-video-example,
                    widget: object,
                    fields:
                      [
                        { label: Label, name: label, widget: string },
                        { label: URL, name: link, widget: string },
                        { label: Description, name: description, widget: text },
                        {
                          label: Resource Type,
                          name: resourceType,
                          widget: string,
                        },
                        {
                          label: Duration,
                          name: durationMinutes,
                          widget: number,
                        },
                        {
                          label: Technical Level,
                          name: technicalLevel,
                          widget: number,
                        },
                      ],
                  },
                ],
            }
